### PR TITLE
add animals table

### PR DESCRIPTION
**Pull request by ANTOINE1128**
## In this PR I have done the following ;
-Used [this template](https://github.com/microverseinc/curriculum-template-databases) to generate a new repo.
- Created a database named vet_clinic.
- Created a table named animals
- Insert data
- Wrote queries for the quests;
## This is the screenshot with the results of my queries  
image

### CODE REVIEW

**Review by topeogunleye — COMMENTED** [review]
Hi @ANTOINE1128, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## 🚫 Invalid Code Review Request 🚫

Thank you for your recent pull request. While we appreciate your effort, we regret to inform you that your changes have been invalidated. Here's the summary of the reasons:

1. **Template Adaptation**: The Microverse Template for the README was not adapted to your project. Instead, you copied and pasted the template as it is, which does not reflect the specific details and requirements of your project. It is crucial to tailor the README to accurately represent your project and provide relevant information to users and contributors.

2. **Lack of Project-specific Information**: A README serves as a crucial document to provide an overview, instructions, and details about your project. By not adapting the template, it fails to provide project-specific information that is necessary for others to understand and contribute to your work effectively.

3. **Documentation Clarity**: README files should be clear, concise, and easy to follow. The direct copy-paste approach can result in inconsistencies and confusion, as the template may contain irrelevant sections or sections that do not align with your project's structure or purpose.

We recommend taking the following steps to resolve the issue:

1. **Adapt the Template**: Carefully review the Microverse Template and adapt it to your project's specific requirements, structure, and goals. Ensure that all sections accurately represent your project, such as its purpose, features, installation instructions, usage examples, and contribution guidelines.

2. **Remove Irrelevant Placeholders**: Remove any placeholders that are meant for only the author of the project. For Example: 
```
> Write a message to encourage readers to support your project
> Give credit to everyone who inspired your codebase.
> Add at least 2 questions new developers would ask when they decide to use your project.
```
4. **Ensure Consistency**: Ensure that the README is consistent in terms of formatting, styling, and grammar. Pay attention to details and make sure the document is easy to read and understand.

Please make the necessary adjustments and resubmit your pull request. We appreciate your understanding and look forward to seeing your improved README that accurately represents your project.

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Gambit142 — COMMENTED** [review]
Hi @ANTOINE1128 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Please include the Key Features and Future Features sections in your README 👍 
- Kindly remove this placeholder sentence from the LICENSE section of your README

Screenshot 2023-07-18 123102

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Review by Gambit142 — COMMENTED** [review]
Hi @ANTOINE1128 👋, 

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Invalid Code Review Request

- Please use `Gitflow` instead of `GitHub` Flow for this project. Your pull request ought to be fro a `feature` branch intending to merge to the `dev` branch as the _**base**_ branch and not the `main` branch as the `base` branch. 👍 😎 

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers, and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Comment by topeogunleye** [comment]
Hi @ANTOINE1128,

While you made a great effort in this project, unfortunately, I cannot proceed to review your code.

## Git flow Not Used ⚠️

- Pull request is to be made from the feature branch into the develop or dev branch not into the main or master branch

Your Code Review Request will be marked as invalid in your Dashboard, so please submit a new one once you are ready 🙏

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag @topeogunleye in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

--------

_Invalid Code Review Request **does not count** into the code reviews limit._

**Pull request closed without merging**
